project:
  type: website

website:
  title: "Chengjie Lu's Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



